### ISSUE TITLE
The localPath you set does not exist

### ISSUE THREAD

**Issue by nadiaks** [robmcvey/cakephp-amazon-s3#4]
I have reinstalled the cakephp-amazon-s3 plugin and had it working perfectly before. I ended up having to update cakephp and for some reason the plugin isn't working anymore. The error that is being thrown back at me is 

The localPath you set does not exist

Error: An Internal Error Has Occurred.

Any help would be appreciated.

**Comment by chinnuvarghese07** [comment]
Please help me out.. am having same problem "The localPath you set does not exist ".
this is my code below,

``` php
App::uses('AmazonS3', 'AmazonS3.Lib');

public function beforeSave($Model) {
       $AmazonS3 = new AmazonS3(array('RTCYGVYYVYVYVVY', 'RTCYCYOGnx', 'buctTest'));
       if (!empty($AmazonS3->bucket) && !empty($AmazonS3->accessKey) && !empty($AmazonS3->secretKey)) {             
         foreach($Model->data as $attachment){
                         $name      = $attachment['filename']['name'];
                         $modelname   = $attachment['model'];
                         $modelid         = $attachment['model_id'];
                         $ImageUrl  = $attachment['filename']['tmp_name']."/".$name;
                         $FileUrl           = $AmazonS3->bucket."/".$modelname."/".$modelid;
                         $AmazonS3->put($ImageUrl , $FileUrl);
                }
        }
}
```

is excatly i have to give in $ImageUrl.
Is that possible to create subfolder $modelname,$modelid alone with this..

Thank you.

**Comment by robmcvey** [comment]
Try;

``` php
foreach ($Model->data as $attachment) {
    $name = $attachment['filename']['name'];
    $ImageUrl = $attachment['filename']['tmp_name'] . DS . $name;
    if (!file_exists($ImageUrl)) {
        debug($ImageUrl);
        throw new Exception("File really does not exist");
    }
}
```

If exception is thrown, the way you are building the `$ImageUrl` var is incorrect.

**Comment by chinnuvarghese07** [comment]
Thank you soo much.
This code works for me..;

if (!empty($AmazonS3->bucket) && !empty($AmazonS3->accessKey) && !empty($AmazonS3->secretKey)) {
                foreach ($Model->data as $attachment) {
                    $name = $attachment['filename']['name'];
                    $modelname  = $attachment['model'];  //Product folder 
                    $modelid    = $attachment['model_id']; //last inserted ID
                    $ImageUrl   = $attachment['filename']['tmp_name'];
                    $FileUrl    = $modelname."/".$modelid;
                    $AmazonS3->put($ImageUrl , $FileUrl);  
                }  
            } else {
                trigger_error('Uploader.Attachment::beforeSave(): To use the S3 transfer, you must supply an accessKey, secretKey and bucket.', E_USER_WARNING);
            }

Can i create subfolder like $FileUrl  (bucket_name/Product/last_insert_id) ..

Thank You.

**Comment by planetwebsolution** [comment]
Still it did not work for me. I've tried 

```
            $name = $_FILES['file']['name'];
            $ImageUrl = $_FILES['file']["tmp_name"] . DS . $name;
            if (!file_exists($ImageUrl)) {
                debug($ImageUrl);
                throw new Exception("File really does not exist");
            }
```

Not working. It continues throw this error.

**Comment by robmcvey** [comment]
That snippet was based on [this comment](https://github.com/robmcvey/cakephp-amazon-s3/issues/4#issuecomment-105533257) so don't just use it verbatim. 

If php's [`file_exists()`](http://php.net/manual/en/function.file-exists.php) returns false, the file <b>does not exist</b>.

Windowz? Check how you build the path:

> On windows, use //computername/share/filename or \computername\share\filename to check files on network shares.

Paste some of your code I'll try and help.
