### ISSUE TITLE
Could not complete the HTTP request

### ISSUE THREAD

**Issue by gurusubedi** [robmcvey/cakephp-amazon-s3#5]
$AmazonS3->put($photo['tmp_name'];

and like asked before i am getting the error as 
 Could not complete the HTTP request

Sample request array

Array
(
    [method] => PUT
    [uri] => Array
        (
            [scheme] => https
            [host] => {imageupload}.s3.amazonaws.com
            [path] => phpZPjzWn
        )

```
[header] => Array
    (
        [Accept] => */*
        [User-Agent] => CakePHP
        [Date] => Tue, 08 Jul 2014 21:12:08 GMT
        [Authorization] => AWS {AKIAI6DGJDHJHDHJHDW2FQ}:in5iSvc2sJHJHJHJ5igMNbLpE=
        [Content-MD5] => Uek+pwowiOe8/b5IERjYYQ==
        [Content-Type] => image/jpeg
        [Content-Length] => 4206
    )

[body] => ÿØÿàJFIFÿÛ„     
```

"" $(4,$&1'-=-157:::#+?D?8C49:7............

Cheers

**Comment by aymanrb** [comment]
I want to use a Bucket name with dots. I keep getting the same error.

Is there a way to fix it ? Changing the bucket name won't fit here unfortunately
