### ISSUE TITLE
Get contents of a bucket

### ISSUE THREAD

**Issue by gurusu** [robmcvey/cakephp-amazon-s3#7]
Hi Rob, i am using your plugin for putting and getting individual images.
How could i add a method in the class to list or get all  the contents of a bucket.

Thank you so much for you time. Its a great plugin.

**Comment by obelich** [comment]
yep please add how to read the content of the s3 to get the file and show the file please

**Comment by robmcvey** [comment]
There may be millions (billions?) of items in a bucket - and AWS limits the listing to 1000 items, so this isn't really viable. 

<blockquote>
GET Bucket (List Objects)
This implementation of the GET operation returns some or all <b>(up to 1000)</b> of the objects in a bucket</blockquote>

If you're building an application, the files on S3 should correspond to something in your database. 

The question "what is in my S3 bucket" is answered in your database, not via an API call.
