### ISSUE TITLE
two or more PUT in line - access denied

### ISSUE THREAD

**Issue by shakalaka** [robmcvey/cakephp-amazon-s3#8]
Hello
When i try to make two PUT in one case with own headers, on upload second file i have access denied.
for example:
$this->AmazonS3->amazonHeaders = array(
	'x-amz-acl' => 'public-read',
	'X-Amz-Meta-ReviewedBy' => 'john.doe@yahoo.biz'
);
$this->AmazonS3->put($fpath, '/test/'.$rand.'/');
$this->AmazonS3->put($fpath, '/test2/'.$rand.'/'); //this line is bad

**Comment by castrike** [comment]
@shakalaka, I ran into the same issue... I fixed it by recreating the s3 object before every upload.
> // First File
> $amazonS3 = new AmazonS3($data);
> $amazonS3 ->amazonHeaders = array(
> 'x-amz-acl' => 'public-read',
> 'X-Amz-Meta-ReviewedBy' => 'john.doe@yahoo.biz'
> );
> $amazonS3->put($fpath, '/test/'.$rand.'/');
> // Second File
> $amazonS3 = new AmazonS3($data);
> $amazonS3 ->amazonHeaders = array(
> 'x-amz-acl' => 'public-read',
> 'X-Amz-Meta-ReviewedBy' => 'john.doe@yahoo.biz'
> );
> $amazonS3->put($fpath, '/test2/'.$rand.'/');

Hope this helps.

**Comment by tjdavenport** [comment]
Wow....

**Comment by castrike** [comment]
@tjdavenport have you tried to re-instantiate the amazon object at the beginning of the loop? 
for(...) {
 $amazons3 = new AmazonS3($data);
$amazons3->amazonHeader= [...];
/// upload file
}
